#!/usr/bin/env bash
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
SCALA_DIR="$HERE/scala"
BUILD_DIR="$HERE/build"
APP="$BUILD_DIR/ssr-app"

if [[ ! -x "$APP" ]]; then
  echo "App not built. Run ./build.sh first." >&2
  exit 1
fi

export SSR_ASSETS_DIR="$HERE/assets"
export SCALA_APP_MAIN="${SCALA_APP_MAIN:-ssr.landmarks.LandmarksMain}"

MODE="$(cat "$BUILD_DIR/.mode" 2>/dev/null || echo jvm)"

# RPC tee: insert `tee` on both sides of the Scala child so we can inspect
# the JSON-RPC stream after the fact. Logs are truncated each run.
RPC_IN_LOG="$BUILD_DIR/rpc-in.log"
RPC_OUT_LOG="$BUILD_DIR/rpc-out.log"
: > "$RPC_IN_LOG"
: > "$RPC_OUT_LOG"

# Build the actual Scala command. The wrapper inherits the env vars the
# Swift parent expects (SCALA_APP_BIN or SCALA_APP_PATH/SCALA_APP_MAIN) —
# but it can't read them by name from inside the Swift process, so we just
# bake the command into the wrapper directly.
WRAPPER="$BUILD_DIR/scala-child-wrapper.sh"
if [[ "$MODE" == "native" ]]; then
  NATIVE_BIN="$BUILD_DIR/ssr-scala-native"
  if [[ ! -x "$NATIVE_BIN" ]]; then
    echo "Native binary missing. Run ./build.sh --native first." >&2
    exit 1
  fi
  CHILD_CMD="exec \"$NATIVE_BIN\""
else
  CHILD_CMD="exec scala-cli run \"$SCALA_DIR\" --main-class \"$SCALA_APP_MAIN\""
fi

cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by run.sh. Inserts tee on both pipe directions so
# RPC traffic to/from the Scala child is captured to log files.
tee "$RPC_IN_LOG" | { $CHILD_CMD; } | tee "$RPC_OUT_LOG"
EOF
chmod +x "$WRAPPER"

SCALA_APP_BIN="$WRAPPER" "$APP"
