package ssr.codegen

import software.amazon.smithy.build.{PluginContext, SmithyBuildPlugin}
import software.amazon.smithy.model.Model
import software.amazon.smithy.model.shapes.*

import java.nio.file.Paths
import scala.jdk.CollectionConverters.*
import scala.jdk.OptionConverters.*

class SwiftCodegenPlugin extends SmithyBuildPlugin:

  private val Namespace = "ssr.internal.protocol"
  private val JsonRpcNotificationTrait = ShapeId.from("jsonrpclib#jsonRpcNotification")
  private val RequiredTrait = ShapeId.from("smithy.api#required")

  override def getName: String = "swift-codegen"

  override def execute(ctx: PluginContext): Unit =
    val output = generate(ctx.getModel)
    ctx.getFileManifest.writeFile(Paths.get("WireTypes.swift"), output)

  /** Renders a Swift type reference for a shape (primitive, list, or named struct). */
  private final class SwiftTypeRef(model: Model) extends ShapeVisitor.Default[String]:
    protected def getDefault(shape: Shape): String = shape.getId.getName
    override def stringShape(s: StringShape): String     = "String"
    override def booleanShape(s: BooleanShape): String   = "Bool"
    override def integerShape(s: IntegerShape): String   = "Int"
    override def longShape(s: LongShape): String         = "Int"
    override def floatShape(s: FloatShape): String       = "Double"
    override def doubleShape(s: DoubleShape): String     = "Double"
    override def listShape(s: ListShape): String =
      val elem = model.expectShape(s.getMember.getTarget).accept(this)
      s"[$elem]"

  /** Renders a top-level Swift declaration for a shape (struct, typealias, or nothing). */
  private final class SwiftDeclaration(
      model: Model,
      typeRef: SwiftTypeRef,
      conformancesFor: ShapeId => String,
  ) extends ShapeVisitor.Default[Option[String]]:
    protected def getDefault(shape: Shape): Option[String] = None

    override def structureShape(s: StructureShape): Option[String] =
      val name         = s.getId.getName
      val conformances = conformancesFor(s.getId)
      val fields = s.getAllMembers.asScala.toList.flatMap { case (fieldName, member) =>
        val target = model.expectShape(member.getTarget)
        target.accept(typeRef) match
          case "Void" => None
          case t      =>
            val opt = if member.hasTrait(RequiredTrait) then "" else "?"
            Some(s"    let $fieldName: $t$opt")
      }
      Some((s"struct $name: $conformances {" :: fields ::: List("}")).mkString("\n"))

    override def listShape(s: ListShape): Option[String] =
      val elem = model.expectShape(s.getMember.getTarget).accept(typeRef)
      Some(s"typealias ${s.getId.getName} = [$elem]")

  private def generate(model: Model): String =
    val inNamespace: Shape => Boolean = _.getId.getNamespace == Namespace

    val operations = model.getOperationShapes.asScala.toList.filter(inNamespace)

    def notification(op: OperationShape): Option[String] =
      op.findTrait(JsonRpcNotificationTrait).toScala.map(_.toNode.expectStringNode.getValue)

    def inputsFor(pred: String => Boolean): Set[ShapeId] =
      operations.flatMap { op =>
        notification(op).filter(pred).flatMap(_ => op.getInput.toScala).toList
      }.toSet

    val eventInputs   = inputsFor(_.startsWith("event/"))
    val commandInputs = inputsFor(!_.startsWith("event/"))

    val conformancesFor: ShapeId => String = id =>
      if eventInputs.contains(id) then "Encodable, Sendable"
      else if commandInputs.contains(id) then "Decodable, Sendable"
      else "Codable, Sendable"

    val typeRef     = SwiftTypeRef(model)
    val declVisitor = SwiftDeclaration(model, typeRef, conformancesFor)

    val namespaceShapes = model.shapes.iterator.asScala.toList
      .filter(inNamespace)
      .sortBy(_.getId.toString)

    val typealiases = namespaceShapes.collect { case s: ListShape => s }.flatMap(_.accept(declVisitor))
    val structs     = namespaceShapes.collect { case s: StructureShape => s }.flatMap(_.accept(declVisitor))

    val notifications = operations.flatMap(notification).sorted
    val methodConsts = notifications.map { method =>
      val constName = method.split("/", 2).last
      s"""    static let $constName = "$method""""
    }

    val sections = scala.collection.mutable.ArrayBuffer.empty[String]
    sections += "// Generated by codegen/swift-plugin — do not edit.\n// Source of truth: smithy/ui.smithy\n\nimport Foundation"

    if typealiases.nonEmpty then
      sections += ("// MARK: - List type aliases\n\n" + typealiases.mkString("\n"))

    sections += ("// MARK: - Wire types (generated from smithy/ui.smithy)\n\n" + structs.mkString("\n\n"))
    sections += ("// MARK: - Method name constants (generated from smithy/ui.smithy)\n\nenum Methods {\n" + methodConsts.mkString("\n") + "\n}")

    sections.mkString("\n\n") + "\n"
